name: algo_learn
description: A new Flutter project.
version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Algorand
  algorand_dart: ^0.0.2-beta.3
  # algorand_dart:
  #   git:
  #     url: https://github.com/RootSoft/algorand-dart.git
  #     ref: master

  # State Management & BLoC
  provider: ^5.0.0
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.5
  equatable: ^2.0.0

  dio: ^4.0.4

  # Fluro - Routing
  fluro: ^2.0.3

  # get_it - Service location
  get_it: ^6.0.0

  # Hive - database
  hive: ^2.0.0
  hive_flutter: ^1.0.0

  # Convert
  convert: ^3.0.0

  cupertino_icons: ^1.0.2

  feather_icons: ^1.1.0-nullsafety.0

  flutter_spinbox: ^0.5.1

  qr_flutter: ^4.0.0

  rxdart: ^0.26.0

  adaptive_dialog: ^0.10.0+5
  url_launcher: ^6.0.3
  clipboard: ^0.1.3
  custom_pop_up_menu: ^1.2.0
  share_plus: ^2.0.3
  path_provider: ^2.0.1
  firebase_core: ^1.17.0
  firebase_database: ^9.0.15
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.5.1
  # fake_cloud_firestore: ^1.3.2
  # firebase_auth_mocks: ^0.8.7
  email_validator: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  animated_theme_switcher: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing framework
  test: ^1.15.5


  # Build Runner & Source Generation
  build_runner: ^2.0.1

  # JSON serialization
  json_serializable: any

  # Hive generation
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
dependency_overrides:
  firebase_core_platform_interface: 4.5.1