// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJrC7qO3JoxZ7aJfsgegmxSqNEqT7n64',
    appId: '1:390074138238:web:dd8e07fea2f8276c28622f',
    messagingSenderId: '390074138238',
    projectId: 'cs189algo',
    authDomain: 'cs189algo.firebaseapp.com',
    databaseURL: 'https://cs189algo-default-rtdb.firebaseio.com',
    storageBucket: 'cs189algo.appspot.com',
    measurementId: 'G-HJBZRVJ852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQ3TEGaV4rpZm-PZHiiXO2tuP491VUsM',
    appId: '1:390074138238:android:507645eaea59fa1928622f',
    messagingSenderId: '390074138238',
    projectId: 'cs189algo',
    databaseURL: 'https://cs189algo-default-rtdb.firebaseio.com',
    storageBucket: 'cs189algo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH4vLiHg5GQ8CALPinP5wiA5X06_7hFuc',
    appId: '1:390074138238:ios:df70a5a62d559a1628622f',
    messagingSenderId: '390074138238',
    projectId: 'cs189algo',
    databaseURL: 'https://cs189algo-default-rtdb.firebaseio.com',
    storageBucket: 'cs189algo.appspot.com',
    iosClientId: '390074138238-h7cs0ekcvpvqf0q95jljj4qvmt3n605t.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
